# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleorder',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='singleorder',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='singleorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='singleorder',
            name='county',
        ),
        migrations.RemoveField(
            model_name='singleorder',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='singleorder',
            name='town',
        ),
        migrations.AddField(
            model_name='singleorder',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
