# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-16 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20190815_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleorder',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
