# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-16 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_singleorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
