# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190816_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleorder',
            name='uploaded_file',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
