# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_singleorder_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleorder',
            name='uploaded_file',
            field=models.FileField(default='', upload_to='images/uploads'),
        ),
        migrations.AlterField(
            model_name='singleorderupload',
            name='uploaded_file',
            field=models.FileField(upload_to='images/uploads'),
        ),
    ]
