# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190819_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleorder',
            name='primary_color',
            field=models.CharField(default=523, max_length=7),
            preserve_default=False,
        ),
    ]
