# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_singleorder_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleorder',
            name='secondary_color',
            field=models.CharField(default=525, max_length=7),
            preserve_default=False,
        ),
    ]
