# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimage',
            old_name='image',
            new_name='add_image',
        ),
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
