# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='brief',
            field=models.TextField(default=''),
        ),
    ]
