# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='brief',
        ),
    ]
