# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short',
            field=models.CharField(default='', max_length=50),
        ),
    ]
