# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upload',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
