# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='upload',
        ),
        migrations.AddField(
            model_name='orderupload',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='checkout.Order'),
        ),
    ]
